export const ROUTES = {
  marketing: {
    home: '/',
  },
  user: {
    app: '/app',
    autopilot: '/autopilot',
    buckets: '/buckets',
    cards: '/cards',
    history: '/history',
    legacy: {
      homeBuckets: '/home/buckets',
      homeHistory: '/home/history',
    },
  },
  dev: {
    root: '/dev',
    scan: '/scan',
    simulate: '/simulate',
    simulations: '/simulations',
    simulationDetail: '/simulations/[simulationId]',
    sessions: '/sessions',
    sessionDetail: '/sessions/[id]',
    activityLab: '/activity',
    vineSimulator: '/vine-simulator',
    bankSimulator: '/bank-simulator',
    admin: '/admin',
    buckets: '/dev/buckets',
    history: '/dev/history',
    statements: '/dev/statements',
    statementDetail: '/dev/statements/[statementId]',
    cards: '/dev/cards',
    cardDetail: '/dev/cards/[cardId]',
    activity: '/dev/activity',
    ingest: '/dev/ingest',
    bank: '/dev/bank',
    evaluator: '/dev/evaluator',
    engine: {
      inspector: '/dev/engine/inspector',
      guardrails: '/dev/engine/guardrails',
    },
  },
} as const;
