import type { JSX } from 'react';
import { getCurrentUserIdOrRedirect } from '@/lib/auth';
import { getUserRealActivityForPeriod, type UnifiedActivityRow } from '@/lib/unified-activity';
import { EmptyList } from '@/components/empty-list';
import { EmptyStateCard } from '@/components/empty-state-card';
import MonthPicker from './client';

type SearchParams = Promise<{ month?: string }>;

type StatementRollup = {
  totalDebitsCents: number;
  totalCreditsCents: number;
  netCents: number;
  pointsEarned: number;
  categoryBreakdown: { category: string; totalCents: number }[];
};

function formatCurrency(value: number): string {
  return `$${value.toFixed(2)}`;
}

function summarize(rows: UnifiedActivityRow[]): StatementRollup {
  const cashEvents = rows.filter((row) => (row.cashDeltaCents ?? 0) !== 0);
  const pointsEvents = rows.filter((row) => (row.pointsDelta ?? row.pointsEarned ?? 0) !== 0);

  const totalDebitsCents = cashEvents
    .filter((row) => (row.cashDeltaCents ?? 0) < 0)
    .reduce((sum, row) => sum + Math.abs(row.cashDeltaCents ?? 0), 0);

  const totalCreditsCents = cashEvents
    .filter((row) => (row.cashDeltaCents ?? 0) > 0)
    .reduce((sum, row) => sum + (row.cashDeltaCents ?? 0), 0);

  const netCents = cashEvents.reduce((sum, row) => sum + (row.cashDeltaCents ?? 0), 0);

  const pointsEarned = pointsEvents
    .filter((row) => (row.pointsDelta ?? row.pointsEarned ?? 0) > 0)
    .reduce((sum, row) => sum + (row.pointsDelta ?? row.pointsEarned ?? 0), 0);

  const categoryTotals = new Map<string, number>();
  for (const row of cashEvents) {
    const delta = row.cashDeltaCents ?? 0;
    if (delta >= 0) continue;
    const key = row.rewardCategory ?? 'Uncategorized';
    categoryTotals.set(key, (categoryTotals.get(key) ?? 0) + Math.abs(delta));
  }

  return {
    totalDebitsCents: totalDebitsCents,
    totalCreditsCents,
    netCents,
    pointsEarned,
    categoryBreakdown: Array.from(categoryTotals.entries()).map(([category, totalCents]) => ({
      category,
      totalCents,
    })),
  };
}

function coerceDate(value: Date | string): Date {
  return value instanceof Date ? value : new Date(value);
}

function StatementTable({ rows }: { rows: UnifiedActivityRow[] }): JSX.Element {
  if (rows.length === 0) {
    return (
      <EmptyStateCard
        title="No activity this period"
        description="Connect accounts or run a simulation to populate this view."
      />
    );
  }

  return (
    <div className="rounded-2xl border border-white/5 bg-slate-950/60 p-4 shadow-lg">
      <table className="min-w-full table-fixed text-sm text-slate-100">
        <thead className="text-xs uppercase tracking-wide text-slate-400">
          <tr>
            <th className="py-2 pr-4 text-left">When</th>
            <th className="py-2 pr-4 text-left">Merchant</th>
            <th className="py-2 pr-4 text-left">Card</th>
            <th className="py-2 pr-4 text-right">Amount</th>
            <th className="py-2 pr-4 text-right">Points</th>
            <th className="py-2 text-right">Source</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-white/5">
          {rows.map((row) => {
            const occurredAt = coerceDate(row.occurredAt);
            return (
              <tr key={row.id}>
                <td className="py-2 pr-4 text-xs text-slate-400">{occurredAt.toLocaleString()}</td>
                <td className="py-2 pr-4">
                  <div className="flex flex-col">
                    <span className="font-medium">
                      {row.merchantName ?? 'Unknown merchant'}
                    </span>
                    <span className="text-xs text-slate-500">
                      {row.mcc ? `MCC ${row.mcc}` : 'MCC unknown'}
                    </span>
                  </div>
                </td>
                <td className="py-2 pr-4 text-xs text-slate-400">
                  {row.cardName ??
                    (row.cardBrand
                      ? `${row.cardBrand}${row.cardLast4 ? ` •••• ${row.cardLast4}` : ''}`
                      : '—')}
                </td>
                <td className="py-2 pr-4 text-right">
                  <AmountCell row={row} />
                </td>
                <td className="py-2 pr-4 text-right">
                  <PointsCell row={row} />
                </td>
                <td className="py-2 text-right">
                  <UserSourceBadge source={row.source} />
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>

      <p className="mt-3 text-xs text-slate-500">
        This is a consolidated analytic statement generated by Cherry from your connected accounts
        and simulations. For official statements, refer to your bank or card issuer.
      </p>
    </div>
  );
}

export default async function StatementsPage({
  searchParams,
}: {
  searchParams: SearchParams;
}): Promise<JSX.Element> {
  const params = await searchParams;
  const now = new Date();
  const defaultMonth = `${now.getUTCFullYear()}-${String(now.getUTCMonth() + 1).padStart(2, '0')}`;
  const selectedMonth =
    params.month && /^\d{4}-\d{2}$/.test(params.month) ? params.month : defaultMonth;
  const [yearPart, monthPart] = selectedMonth.split('-');
  const year = Number(yearPart);
  const month = Number(monthPart);

  const userId = await getCurrentUserIdOrRedirect('/statements');
  const rows = await getUserRealActivityForPeriod(userId, { year, month });
  const stats = summarize(rows);

  return (
    <main className="flex-1 overflow-y-auto px-6 py-8">
      <div className="mx-auto max-w-6xl space-y-6">
        <header className="space-y-1">
          <p className="text-xs uppercase tracking-label text-pink-200">Statements</p>
          <h1 className="text-3xl font-semibold text-white">Periodic statement</h1>
          <p className="text-slate-300">
            Monthly rollup of your real card activity. Switch months to review spend, credits, and
            points.
          </p>
        </header>

        <MonthPicker initialMonth={selectedMonth} />

        <section className="grid gap-4 md:grid-cols-4">
          <SummaryCard
            label="Total debits"
            value={formatCurrency(stats.totalDebitsCents / 100)}
          />
          <SummaryCard
            label="Total credits"
            value={formatCurrency(stats.totalCreditsCents / 100)}
          />
          <SummaryCard
            label="Net"
            value={formatCurrency(stats.netCents / 100)}
            tone={stats.netCents >= 0 ? 'positive' : 'negative'}
          />
          <SummaryCard label="Points earned" value={`${stats.pointsEarned}`} tone="positive" />
        </section>

        <section className="grid gap-4 md:grid-cols-1">
          <div className="rounded-2xl border border-white/5 bg-slate-950/60 p-4 shadow-lg">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs uppercase tracking-label text-slate-400">Category breakdown</p>
                <p className="text-xs text-slate-500">
                  Real debits only · excludes simulations and pending items.
                </p>
              </div>
            </div>
            <ul className="mt-2 space-y-1 text-sm text-slate-100">
              {stats.categoryBreakdown.length === 0 ? (
                <EmptyList
                  title="No real spend this month"
                  description="When real transaction debits land, Cherry will break them down by category here."
                />
              ) : (
                stats.categoryBreakdown.map((cat) => (
                  <li key={cat.category} className="flex items-center justify-between">
                    <span>{cat.category}</span>
                    <span className="text-slate-300">{formatCurrency(cat.totalCents / 100)}</span>
                  </li>
                ))
              )}
            </ul>
          </div>
        </section>

        <StatementTable rows={rows} />
      </div>
    </main>
  );
}

function SummaryCard({
  label,
  value,
  tone = 'neutral',
}: {
  label: string;
  value: string;
  tone?: 'neutral' | 'positive' | 'negative';
}): JSX.Element {
  const toneClass =
    tone === 'positive'
      ? 'border-emerald-500/40 bg-emerald-500/10'
      : tone === 'negative'
        ? 'border-pink-500/40 bg-pink-500/10'
        : 'border-white/5 bg-white/5';
  return (
    <div className={`rounded-2xl border ${toneClass} p-4 shadow-lg`}>
      <p className="text-xs uppercase tracking-label text-slate-400">{label}</p>
      <p className="mt-2 text-2xl font-semibold text-white">{value}</p>
    </div>
  );
}

function AmountCell({ row }: { row: UnifiedActivityRow }): JSX.Element {
  const cashDelta = row.cashDeltaCents ?? 0;
  if (!cashDelta) {
    return <span className="text-xs text-slate-500">—</span>;
  }

  const sign = cashDelta < 0 ? '-' : '+';
  const cls = cashDelta < 0 ? 'font-semibold text-rose-300' : 'font-semibold text-emerald-300';
  const abs = Math.abs(cashDelta) / 100;

  return (
    <span className={cls}>
      {sign}
      {abs.toFixed(2)} {row.currency}
    </span>
  );
}

function PointsCell({ row }: { row: UnifiedActivityRow }): JSX.Element {
  const pts = row.pointsDelta ?? row.pointsEarned ?? 0;
  if (!pts) {
    return <span className="text-xs text-slate-500">—</span>;
  }

  const sign = pts < 0 ? '-' : '+';
  const cls = pts < 0 ? 'text-xs text-rose-300' : 'text-xs text-emerald-300';

  return (
    <span className={cls}>
      {sign}
      {Math.abs(pts)}
    </span>
  );
}

function UserSourceBadge({ source }: { source: string }): JSX.Element {
  let label = 'Activity';
  switch (source) {
    case 'BANK_FEED':
    case 'STATEMENT_VIEW':
      label = 'Bank';
      break;
    default:
      label = 'Activity';
  }
  return (
    <span className="rounded-full bg-white/5 px-2 py-0.5 text-[10px] uppercase tracking-wide text-slate-200">
      {label}
    </span>
  );
}
