import type { JSX } from 'react';
import { getCurrentUserIdOrRedirect } from '@/lib/auth';
import { getUnifiedActivityForUser, type UnifiedActivityRow } from '@/lib/unified-activity';
import MonthPicker from './client';

type SearchParams = Promise<{ month?: string }>;

function formatCurrency(value: number): string {
  return `$${value.toFixed(2)}`;
}

function summarize(rows: UnifiedActivityRow[]) {
  let totalDebit = 0;
  let totalCredit = 0;
  let points = 0;
  let realTotal = 0;
  let simulatedTotal = 0;
  const categoryTotals: Record<string, number> = {};

  rows.forEach((row) => {
    const amount = row.amount;
    if (row.direction === 'DEBIT') {
      totalDebit += amount;
    } else {
      totalCredit += amount;
    }
    if (row.pointsEarned) points += row.pointsEarned;

    const isReal = row.source === 'BANK_FEED' || row.source === 'STATEMENT_VIEW';
    if (isReal) {
      realTotal += amount;
    } else {
      simulatedTotal += amount;
    }

    const category = row.rewardCategory ?? 'Uncategorized';
    categoryTotals[category] = (categoryTotals[category] ?? 0) + amount;
  });

  const net = totalCredit - totalDebit;
  const totalActivity = realTotal + simulatedTotal || 1;

  return {
    totalDebit,
    totalCredit,
    net,
    points,
    realShare: (realTotal / totalActivity) * 100,
    simulatedShare: (simulatedTotal / totalActivity) * 100,
    categoryTotals,
  };
}

function coerceDate(value: Date | string): Date {
  return value instanceof Date ? value : new Date(value);
}

function StatementTable({ rows }: { rows: UnifiedActivityRow[] }): JSX.Element {
  if (rows.length === 0) {
    return (
      <div className="rounded-2xl border border-white/5 bg-white/5 p-4 shadow-lg">
        <p className="text-sm text-slate-300">
          No activity in this period. Connect accounts or run a simulation to populate this view.
        </p>
      </div>
    );
  }

  return (
    <div className="rounded-2xl border border-white/5 bg-slate-950/60 p-4 shadow-lg">
      <table className="min-w-full table-fixed text-sm text-slate-100">
        <thead className="text-xs uppercase tracking-wide text-slate-400">
          <tr>
            <th className="py-2 pr-4 text-left">When</th>
            <th className="py-2 pr-4 text-left">Merchant</th>
            <th className="py-2 pr-4 text-left">Card</th>
            <th className="py-2 pr-4 text-right">Amount</th>
            <th className="py-2 pr-4 text-right">Points</th>
            <th className="py-2 text-right">Source</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-white/5">
          {rows.map((row) => {
            const occurredAt = coerceDate(row.occurredAt);
            return (
              <tr key={row.id}>
                <td className="py-2 pr-4 text-xs text-slate-400">{occurredAt.toLocaleString()}</td>
                <td className="py-2 pr-4">
                  <div className="flex flex-col">
                    <span className="font-medium">
                      {row.merchantName ?? 'Unknown merchant'}
                    </span>
                    <span className="text-xs text-slate-500">
                      {row.mcc ? `MCC ${row.mcc}` : 'MCC unknown'}
                    </span>
                  </div>
                </td>
                <td className="py-2 pr-4 text-xs text-slate-400">
                  {row.cardName ??
                    (row.cardBrand
                      ? `${row.cardBrand}${row.cardLast4 ? ` •••• ${row.cardLast4}` : ''}`
                      : '—')}
                </td>
                <td className="py-2 pr-4 text-right">
                  <span
                    className={
                      row.direction === 'DEBIT'
                        ? 'font-semibold text-slate-100'
                        : 'font-semibold text-emerald-300'
                    }
                  >
                    {row.direction === 'DEBIT' ? '-' : '+'}
                    {row.amount.toFixed(2)} {row.currency}
                  </span>
                </td>
                <td className="py-2 pr-4 text-right text-xs text-emerald-300">
                  {row.pointsEarned != null ? `+${row.pointsEarned}` : '—'}
                </td>
                <td className="py-2 text-right">
                  <span className="rounded-full bg-white/5 px-2 py-0.5 text-[10px] uppercase tracking-wide text-slate-200">
                    {row.source}
                  </span>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>

      <p className="mt-3 text-xs text-slate-500">
        This is a consolidated analytic statement generated by Cherry from your connected accounts
        and simulations. For official statements, refer to your bank or card issuer.
      </p>
    </div>
  );
}

export default async function StatementsPage({
  searchParams,
}: {
  searchParams: SearchParams;
}): Promise<JSX.Element> {
  const params = await searchParams;
  const now = new Date();
  const defaultMonth = `${now.getUTCFullYear()}-${String(now.getUTCMonth() + 1).padStart(2, '0')}`;
  const selectedMonth =
    params.month && /^\d{4}-\d{2}$/.test(params.month) ? params.month : defaultMonth;
  const [yearPart, monthPart] = selectedMonth.split('-');
  const year = Number(yearPart);
  const month = Number(monthPart);

  const userId = await getCurrentUserIdOrRedirect('/statements');
  const rows = await getUnifiedActivityForUser(userId, {
    limit: 1000,
    periodFilter: { year, month },
  });
  const stats = summarize(rows);

  return (
    <main className="flex-1 overflow-y-auto px-6 py-8">
      <div className="mx-auto max-w-6xl space-y-6">
        <header className="space-y-1">
          <p className="text-xs uppercase tracking-label text-pink-200">Statements</p>
          <h1 className="text-3xl font-semibold text-white">Periodic statement</h1>
          <p className="text-slate-300">
            Monthly rollup across real and simulated activity. Switch months to review spend, credits,
            and points.
          </p>
        </header>

        <MonthPicker initialMonth={selectedMonth} />

        <section className="grid gap-4 md:grid-cols-4">
          <SummaryCard label="Total debits" value={formatCurrency(stats.totalDebit)} />
          <SummaryCard label="Total credits" value={formatCurrency(stats.totalCredit)} />
          <SummaryCard
            label="Net"
            value={formatCurrency(stats.net)}
            tone={stats.net >= 0 ? 'positive' : 'negative'}
          />
          <SummaryCard label="Points earned" value={`${stats.points}`} tone="positive" />
        </section>

        <section className="grid gap-4 md:grid-cols-2">
          <div className="rounded-2xl border border-white/5 bg-white/5 p-4 shadow-lg">
            <p className="text-xs uppercase tracking-label text-slate-400">Mix</p>
            <p className="text-sm text-slate-200">
              Real: {stats.realShare.toFixed(1)}% · Simulated: {stats.simulatedShare.toFixed(1)}%
            </p>
          </div>

          <div className="rounded-2xl border border-white/5 bg-white/5 p-4 shadow-lg">
            <p className="text-xs uppercase tracking-label text-slate-400">Category breakdown</p>
            <ul className="mt-2 space-y-1 text-sm text-slate-100">
              {Object.entries(stats.categoryTotals).map(([category, amount]) => (
                <li key={category} className="flex items-center justify-between">
                  <span>{category}</span>
                  <span className="text-slate-300">{formatCurrency(amount)}</span>
                </li>
              ))}
            </ul>
          </div>
        </section>

        <StatementTable rows={rows} />
      </div>
    </main>
  );
}

function SummaryCard({
  label,
  value,
  tone = 'neutral',
}: {
  label: string;
  value: string;
  tone?: 'neutral' | 'positive' | 'negative';
}): JSX.Element {
  const toneClass =
    tone === 'positive'
      ? 'border-emerald-500/40 bg-emerald-500/10'
      : tone === 'negative'
        ? 'border-pink-500/40 bg-pink-500/10'
        : 'border-white/5 bg-white/5';
  return (
    <div className={`rounded-2xl border ${toneClass} p-4 shadow-lg`}>
      <p className="text-xs uppercase tracking-label text-slate-400">{label}</p>
      <p className="mt-2 text-2xl font-semibold text-white">{value}</p>
    </div>
  );
}
